### ISSUE TITLE
Can `svelte-sound` be used manually?

### ISSUE THREAD

**Issue by iguesspaul** [Rajaniraiyn/svelte-sound#25]
Title.

I would like to use it for both some button interactions but also for some game events (clearing a level for example)

Is this possible

**Comment by Rajaniraiyn** [comment]
Currently it is not possible in `svelte-sound` but you can directly use [Howler.js](https://howlerjs.com/) for this.

It is bit harder to implement as most of the browsers don't allow audio without user interaction (but there are workarounds for games kinda apps)

**Comment by Rajaniraiyn** [comment]
@iguesspaul Can you suggest an example API that you would like to use for `svelte-sound` manually. Like below

```ts
import { SyntheticSound } from "svelte-sound"
import success_sound from "./success.mp4"

const options = {
// options for svelte-sound
}

const levelClearedEffect = new SyntheticSound(success_sound, options);

levelClearedEffect.play()
```
will this kind of API will be easier to use or you would like something else?

**Comment by iguesspaul** [comment]
The example api you had shown would be suited perfectly for me. However, the only extra thing I would perhaps like to see is the ability to reuse sounds (play them more than once, which in howler involves a whole reloading process). For the rest, this has been great library to use

**Comment by Rajaniraiyn** [comment]
@iguesspaul You're most welcome for the feedback. I'd like to inform you that the most recent release of `svelte-sound` (v0.6.0) now includes a feature that allows manual sound playback without the need for DOM elements. For further insights, please refer to the details provided in the [README.md](https://github.com/Rajaniraiyn/svelte-sound#sound-class).
