### ISSUE TITLE
What are the audio formats and codecs supported ?

### ISSUE THREAD

**Issue by thismatters** [Rajaniraiyn/svelte-sound#35]
The docs only mention `.mp4`, what codecs are supported for that format?

Are there any other formats supported?

**Comment by Rajaniraiyn** [comment]
Thanks to reaching me out.

> Howler.js supports a wide array of audio codecs that have varying browser support ("mp3", "opus", "ogg", "wav", "aac", "m4a", "m4b", "mp4", "webm", ...), but if you want full browser coverage you still need to use at least two of them. If your goal is to have the best balance of small filesize and high quality, based on extensive production testing, your best bet is to default to webm and fallback to mp3. webm has nearly full browser coverage with a great combination of compression and quality. You'll need the mp3 fallback for Internet Explorer.

Since `svelte-sound` uses [Howler.js](https://howlerjs.com/) library under-the-hood you can have a look at their recomendations [here](https://github.com/goldfire/howler.js?tab=readme-ov-file#format-recommendations).

I'll update the same in the docs too.
